import { type Config, type Product, type Category, type Price, unknown, verified } from './model'

const seed = (cents: number): Price => ({ cents, verified: false, source: 'online' })
// Frozen v1 shipped data, used only to distinguish defaults from intentional edits.
// Never update these values when changing the current menu.
// https://www.ubereats.com/ca/store/mucho-burrito-1600-15th-ave-unit-145/3J5voFnUUfG2JOdE4Erf_w
const product = (
  id: string,
  name: string,
  category: Category,
  amount: number | null,
  customizable = false,
  description = '',
): Product => ({
  id,
  name,
  category,
  price: amount === null ? unknown() : seed(amount),
  customizable,
  description,
  taxClass: 'FOOD',
  deposit: verified(0),
  enabled: true,
  lto: false,
  proteinOverrides: {},
  extraOverrides: {},
  excludedProteinIds: [],
  excludedExtraIds: [],
})
export const legacyDefaults: Config = {
  version: 1,
  defaultsVersion: 1,
  taxes: { gstBasisPoints: 500, pstBasisPoints: 700 },
  products: [
    product(
      'small-burrito',
      'Small Burrito',
      'Burritos',
      1345,
      true,
      'A little lighter. All the flavour.',
    ),
    product(
      'regular-burrito',
      'Regular Burrito',
      'Burritos',
      1545,
      true,
      'The go-to, made your way.',
    ),
    product(
      'mucho-burrito',
      'Mucho Burrito',
      'Burritos',
      1915,
      true,
      'Big appetite. Bigger burrito.',
    ),
    product('bowl', 'Bowl', 'Bowls / Salads', 1675, true, 'All the good stuff, in a bowl.'),
    product('salad', 'Salad', 'Bowls / Salads', 1675, true, 'Fresh, crisp and made your way.'),
    product('taco-solo', 'Taco Solo', 'Tacos', 545, true, 'One taco, your choice of protein.'),
    product('taco-trio', 'Taco Trio', 'Tacos', 1535, true, 'Three tacos. One great choice.'),
    product(
      'quesadilla',
      'Quesadilla',
      'Quesadilla',
      1355,
      true,
      'Toasted tortilla, melted cheese.',
    ),
    ...[
      ['salsa-flight', 'Salsa Flight', 795],
      ['signature-fries-regular', 'Signature Mercado Fries · Regular', 599],
      ['signature-fries-mucho', 'Signature Mercado Fries · Mucho', 962],
      ['zesty-fries-regular', 'Zesty Fresca Fries · Regular', 720],
      ['zesty-fries-mucho', 'Zesty Fresca Fries · Mucho', 1020],
      ['queso-fries-regular', 'Creamy Queso Fries · Regular', 720],
      ['queso-fries-mucho', 'Creamy Queso Fries · Mucho', 1020],
      ['loaded-nachos', 'Loaded Nachos', 840],
      ['chips-queso', 'Chips + Queso', 595],
      ['chips-guacamole', 'Chips + Guacamole', 595],
      ['chips-salsa', 'Chips + Salsa', 495],
      ['salsa', 'Salsa · 4oz', 275],
      ['queso', 'Queso · 4oz', 375],
      ['guacamole', 'Guacamole · 4oz', 375],
      ['extra-tortilla', '10-inch Tortilla', 55],
    ].map(([id, name, amount]) => product(String(id), String(name), 'Sides', Number(amount))),
    product('chips', 'Chips', 'Sides', null),
    ...[
      // Canned/Bottled Pop listing prices seed the named Pepsi variants; verify each flavour.
      ['Canned Pepsi', 'SODA', 325],
      ['Canned Diet Pepsi', 'SODA', 325],
      ['Canned Ginger Ale', 'SODA', 325],
      ['Bottled Pepsi', 'SODA', 425],
      ['Jarritos', 'SODA', 425],
      ['Bottled Water', 'NON_SODA_DRINK', 325],
      ['Iced Tea', 'NON_SODA_DRINK', 425],
      ['Juice', 'NON_SODA_DRINK', 425],
      ['Montellier Sparkling Water', 'NON_SODA_DRINK', 395],
      ['Fountain Soda', 'SODA', null],
      ['4 Canned Pepsi Drinks', 'SODA', 895],
      ['4 Bottled Pepsi Drinks', 'SODA', 1395],
      ['4 Jarritos', 'SODA', 1395],
    ].map(([name, taxClass, amount]) => ({
      ...product(
        String(name).toLowerCase().replaceAll(' ', '-'),
        String(name),
        'Drinks',
        amount === null ? null : Number(amount),
      ),
      taxClass: taxClass as Product['taxClass'],
      deposit: name === 'Fountain Soda' ? verified(0) : unknown(),
    })),
    {
      ...product(
        'corona-cero',
        'Corona Cero',
        'Drinks',
        695,
        false,
        'Check local availability & beverage tax class before enabling.',
      ),
      taxClass: 'NON_SODA_DRINK',
      deposit: unknown(),
      enabled: false,
    },
    product('churros', 'Churro Fries', 'Desserts', 395),
    product('cookie', 'Chocolate Chunk Cookies', 'Desserts', 295),
    product('mucho-churros', 'Mucho Churro Fries', 'Desserts', 1495),
    product('mucho-cookies', 'Mucho Cookies', 'Desserts', 1295),
    product(
      'signature-burrito',
      'Mucho’s Way Burrito',
      'More',
      1345,
      true,
      'Signature recipe. Choose your protein.',
    ),
    product('signature-bowl', 'Mucho’s Way Bowl', 'More', 1675, true),
    product('shiitake-burrito', 'Signature Shiitake Carnitas Burrito', 'More', 1075),
    product('shiitake-bowl', 'Signature Shiitake Carnitas Bowl', 'More', 1375),
    ...[
      ['burrito-bundle-4', 'Burrito Bundle · 4 pcs', 4995],
      ['burrito-bundle-6', 'Burrito Bundle · 6 pcs', 6995],
      ['burrito-bundle-10', 'Burrito Bundle · 10 pcs', 9495],
      ['bowl-bar', 'BYO Bowl Bar · Serves 4–6', 8400],
      ['taco-kit-4', 'Take Home Taco Kit · Serves 4', 5999],
      ['taco-kit-6', 'Take Home Taco Kit · Serves 6', 8499],
      ['taco-kit-8', 'Take Home Taco Kit · Serves 8', 10999],
    ].map(([id, name, amount]) => ({
      ...product(
        String(id),
        String(name),
        'More',
        Number(amount),
        false,
        'Standard bundle. Configure any premium variant as its own product.',
      ),
      enabled: false,
    })),
    {
      ...product('honey-chili-burrito', 'Honey Chili Pepper Chicken Burrito', 'More', 1670),
      lto: true,
    },
    { ...product('honey-chili-bowl', 'Honey Chili Pepper Chicken Bowl', 'More', 1800), lto: true },
    { ...product('limited-time', 'Limited-time Special', 'More', null), enabled: false, lto: true },
  ],
  proteins: [
    'Grilled Chicken',
    'Crispy Chicken',
    'Chorizo',
    'Ancho Ground Beef',
    'Pork Carnitas',
    'Veggies',
    'Steak',
    'Beef Barbacoa',
    'Shiitake Carnitas',
  ].map((name) => ({
    id: name.toLowerCase().replaceAll(' ', '-'),
    name,
    price: unknown(),
    enabled: true,
  })),
  extras: ['Guacamole', 'Queso', 'Extra Protein', 'Extra Cheese'].map((name) => ({
    id: name.toLowerCase().replaceAll(' ', '-'),
    name,
    price: unknown(),
    enabled: true,
  })),
}
